import os

from dotenv import load_dotenv
from google import genai


load_dotenv()


GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")


if not GEMINI_API_KEY:
    raise RuntimeError(
        "GEMINI_API_KEY is not configured. "
        "Please add it to the backend .env file."
    )


client = genai.Client(
    api_key=GEMINI_API_KEY
)


SYSTEM_INSTRUCTION = """
You are BTIP Business Turnaround Assistant.

BTIP stands for Business Turnaround Intelligence Platform.

Your role is to help users understand business financial health,
financial risks, crisis indicators, forecasts, recovery simulations,
recommendations, and alerts generated by BTIP.

You are a business and financial analysis assistant.

Rules:

1. Use the BTIP data provided to you as the primary source of truth.

2. Do not invent financial values, company information, analysis
   results, forecasts, or recommendations.

3. If required information is unavailable, clearly say that the
   information is not available.

4. Explain financial concepts in simple language when the user
   asks for an explanation.

5. When discussing financial problems, identify the most important
   issue first.

6. When suggesting actions, prioritize practical business
   turnaround actions.

7. Do not claim that your suggestions are guaranteed to improve
   the company's performance.

8. Clearly distinguish between:
   - actual BTIP results
   - interpretation of those results
   - general business suggestions

9. Keep responses concise unless the user asks for a detailed
   explanation.

10. Never pretend to have access to data that was not provided.

You are specifically an assistant for BTIP, not a generic chatbot.
"""


def build_company_context(company_data):
    if not company_data:
        return """
No company has been selected or no company data is currently
available.
"""

    return f"""
CURRENT BTIP COMPANY CONTEXT

Company:
{company_data.get("company_name", "Unknown")}

Industry:
{company_data.get("industry", "Unknown")}

Financial Metrics:

Revenue:
{company_data.get("revenue", "Not available")}

Expenses:
{company_data.get("expenses", "Not available")}

Profit:
{company_data.get("profit", "Not available")}

Profit Margin:
{company_data.get("profit_margin", "Not available")}

Assets:
{company_data.get("assets", "Not available")}

Liabilities:
{company_data.get("liabilities", "Not available")}

Debt:
{company_data.get("debt", "Not available")}

Equity:
{company_data.get("equity", "Not available")}

Cash:
{company_data.get("cash", "Not available")}

Current Assets:
{company_data.get("current_assets", "Not available")}

Current Liabilities:
{company_data.get("current_liabilities", "Not available")}

Current Ratio:
{company_data.get("current_ratio", "Not available")}

Debt-to-Equity:
{company_data.get("debt_to_equity", "Not available")}

Operating Cash Flow:
{company_data.get("operating_cash_flow", "Not available")}

Investing Cash Flow:
{company_data.get("investing_cash_flow", "Not available")}

Financing Cash Flow:
{company_data.get("financing_cash_flow", "Not available")}

Net Cash Flow:
{company_data.get("net_cash_flow", "Not available")}

Risk Score:
{company_data.get("risk_score", "Not available")}

Risk Level:
{company_data.get("risk_level", "Not available")}

Crisis Detected:
{company_data.get("crisis_detected", "Not available")}

Recommendations:
{company_data.get("recommendations", "Not available")}

Alerts:
{company_data.get("alerts", "Not available")}
"""


def ask_gemini(question, company_data=None):
    context = build_company_context(company_data)

    prompt = f"""
{context}

USER QUESTION:

{question}

Answer the user's question using the BTIP company context above.
"""

    try:
        interaction = client.interactions.create(
            model="gemini-3.6-flash",
            input=prompt,
            system_instruction=SYSTEM_INSTRUCTION
        )

        return interaction.output_text

    except Exception as exc:
        print("Gemini API error:", exc)

        raise RuntimeError(
            "Unable to generate a response from the Gemini API."
        )