from io import BytesIO
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
    KeepTogether,
)
from reportlab.graphics.shapes import Drawing
from reportlab.graphics.charts.barcharts import VerticalBarChart


# =========================================================
# Formatting Helpers
# =========================================================

def currency(value):
    if value is None:
        return "N/A"

    try:
        return f"Rs. {float(value):,.0f}"
    except (TypeError, ValueError):
        return "N/A"


def number(value, decimals=2):
    if value is None:
        return "N/A"

    try:
        return f"{float(value):.{decimals}f}"
    except (TypeError, ValueError):
        return "N/A"


def percentage(value):
    if value is None:
        return "N/A"

    try:
        return f"{float(value):.2f}%"
    except (TypeError, ValueError):
        return "N/A"


def safe_text(value):
    if value is None:
        return "N/A"

    return str(value)


# =========================================================
# PDF Header / Footer
# =========================================================

def draw_header_footer(canvas, doc):
    canvas.saveState()

    width, height = A4

    # Header line
    canvas.setStrokeColor(colors.HexColor("#d1d5db"))
    canvas.line(
        18 * mm,
        height - 15 * mm,
        width - 18 * mm,
        height - 15 * mm,
    )

    # Header text
    canvas.setFont("Helvetica-Bold", 9)
    canvas.setFillColor(colors.HexColor("#1f2937"))
    canvas.drawString(
        18 * mm,
        height - 11 * mm,
        "BTIP"
    )

    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.HexColor("#6b7280"))
    canvas.drawRightString(
        width - 18 * mm,
        height - 11 * mm,
        "Business Turnaround Intelligence Platform"
    )

    # Footer line
    canvas.setStrokeColor(colors.HexColor("#d1d5db"))
    canvas.line(
        18 * mm,
        14 * mm,
        width - 18 * mm,
        14 * mm,
    )

    # Footer
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.HexColor("#6b7280"))

    canvas.drawString(
        18 * mm,
        9 * mm,
        "Generated by BTIP"
    )

    canvas.drawRightString(
        width - 18 * mm,
        9 * mm,
        f"Page {doc.page}"
    )

    canvas.restoreState()


# =========================================================
# Styles
# =========================================================

def create_styles():

    styles = getSampleStyleSheet()

    styles.add(
        ParagraphStyle(
            name="BTIPTitle",
            parent=styles["Title"],
            fontName="Helvetica-Bold",
            fontSize=25,
            leading=30,
            alignment=TA_CENTER,
            textColor=colors.HexColor("#1f2937"),
            spaceAfter=10,
        )
    )

    styles.add(
        ParagraphStyle(
            name="BTIPSubtitle",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=12,
            leading=16,
            alignment=TA_CENTER,
            textColor=colors.HexColor("#6b7280"),
            spaceAfter=6,
        )
    )

    styles.add(
        ParagraphStyle(
            name="SectionHeading",
            parent=styles["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=15,
            leading=20,
            textColor=colors.HexColor("#111827"),
            spaceBefore=10,
            spaceAfter=10,
        )
    )

    styles.add(
        ParagraphStyle(
            name="SubHeading",
            parent=styles["Heading3"],
            fontName="Helvetica-Bold",
            fontSize=11,
            leading=15,
            textColor=colors.HexColor("#1f2937"),
            spaceBefore=6,
            spaceAfter=6,
        )
    )

    styles.add(
        ParagraphStyle(
            name="Body",
            parent=styles["BodyText"],
            fontName="Helvetica",
            fontSize=9.5,
            leading=15,
            textColor=colors.HexColor("#374151"),
            spaceAfter=6,
        )
    )

    styles.add(
        ParagraphStyle(
            name="Small",
            parent=styles["BodyText"],
            fontName="Helvetica",
            fontSize=8,
            leading=11,
            textColor=colors.HexColor("#6b7280"),
        )
    )

    styles.add(
        ParagraphStyle(
            name="KPIValue",
            parent=styles["BodyText"],
            fontName="Helvetica-Bold",
            fontSize=13,
            leading=17,
            textColor=colors.HexColor("#111827"),
        )
    )

    styles.add(
        ParagraphStyle(
            name="KPILabel",
            parent=styles["BodyText"],
            fontName="Helvetica",
            fontSize=8,
            leading=11,
            textColor=colors.HexColor("#6b7280"),
        )
    )

    styles.add(
        ParagraphStyle(
            name="Positive",
            parent=styles["BodyText"],
            fontName="Helvetica-Bold",
            fontSize=10,
            textColor=colors.HexColor("#15803d"),
        )
    )

    styles.add(
        ParagraphStyle(
            name="Warning",
            parent=styles["BodyText"],
            fontName="Helvetica-Bold",
            fontSize=10,
            textColor=colors.HexColor("#b45309"),
        )
    )

    styles.add(
        ParagraphStyle(
            name="Danger",
            parent=styles["BodyText"],
            fontName="Helvetica-Bold",
            fontSize=10,
            textColor=colors.HexColor("#b91c1c"),
        )
    )

    return styles


# =========================================================
# Tables
# =========================================================

def create_kpi_table(items, styles):

    cells = []

    for label, value in items:

        cells.append(
            [
                Paragraph(label, styles["KPILabel"]),
                Spacer(1, 3),
                Paragraph(value, styles["KPIValue"]),
            ]
        )

    table = Table(
        [cells],
        colWidths=[43 * mm] * len(cells),
    )

    table.setStyle(
        TableStyle(
            [
                (
                    "BACKGROUND",
                    (0, 0),
                    (-1, -1),
                    colors.white,
                ),
                (
                    "BOX",
                    (0, 0),
                    (-1, -1),
                    0.6,
                    colors.HexColor("#e5e7eb"),
                ),
                (
                    "INNERGRID",
                    (0, 0),
                    (-1, -1),
                    0.6,
                    colors.HexColor("#e5e7eb"),
                ),
                (
                    "VALIGN",
                    (0, 0),
                    (-1, -1),
                    "TOP",
                ),
                (
                    "LEFTPADDING",
                    (0, 0),
                    (-1, -1),
                    10,
                ),
                (
                    "RIGHTPADDING",
                    (0, 0),
                    (-1, -1),
                    10,
                ),
                (
                    "TOPPADDING",
                    (0, 0),
                    (-1, -1),
                    10,
                ),
                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, -1),
                    10,
                ),
            ]
        )
    )

    return table


def create_metric_table(rows, styles):

    data = [
        [
            Paragraph("<b>Metric</b>", styles["Body"]),
            Paragraph("<b>Value</b>", styles["Body"]),
        ]
    ]

    for label, value in rows:
        data.append(
            [
                Paragraph(safe_text(label), styles["Body"]),
                Paragraph(
                    f"<b>{safe_text(value)}</b>",
                    styles["Body"],
                ),
            ]
        )

    table = Table(
        data,
        colWidths=[85 * mm, 85 * mm],
    )

    table.setStyle(
        TableStyle(
            [
                (
                    "BACKGROUND",
                    (0, 0),
                    (-1, 0),
                    colors.HexColor("#f3f4f6"),
                ),
                (
                    "GRID",
                    (0, 0),
                    (-1, -1),
                    0.5,
                    colors.HexColor("#d1d5db"),
                ),
                (
                    "VALIGN",
                    (0, 0),
                    (-1, -1),
                    "MIDDLE",
                ),
                (
                    "LEFTPADDING",
                    (0, 0),
                    (-1, -1),
                    8,
                ),
                (
                    "RIGHTPADDING",
                    (0, 0),
                    (-1, -1),
                    8,
                ),
                (
                    "TOPPADDING",
                    (0, 0),
                    (-1, -1),
                    7,
                ),
                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, -1),
                    7,
                ),
            ]
        )
    )

    return table


# =========================================================
# Revenue Chart
# =========================================================

def create_revenue_chart(historical, predictions):

    drawing = Drawing(
        165 * mm,
        75 * mm,
    )

    chart = VerticalBarChart()

    chart.x = 12 * mm
    chart.y = 12 * mm
    chart.height = 50 * mm
    chart.width = 140 * mm

    chart.valueAxis.valueMin = 0

    all_values = historical + predictions

    if all_values:
        chart.valueAxis.valueMax = max(all_values) * 1.2

    chart.valueAxis.valueStep = (
        max(all_values) / 5
        if all_values
        else 1
    )

    chart.categoryAxis.labels.fontName = "Helvetica"
    chart.categoryAxis.labels.fontSize = 7

    labels = []

    for index in range(len(historical)):
        labels.append(f"P{index + 1}")

    for index in range(len(predictions)):
        labels.append(f"F{index + 1}")

    chart.categoryAxis.categoryNames = labels

    # ReportLab requires series data.
    # Historical bars and forecast bars are represented
    # in separate series.

    historical_series = []

    forecast_series = []

    for index in range(len(all_values)):

        if index < len(historical):
            historical_series.append(
                historical[index]
            )
            forecast_series.append(0)

        else:
            historical_series.append(0)
            forecast_series.append(
                predictions[
                    index - len(historical)
                ]
            )

    chart.data = [
        historical_series,
        forecast_series,
    ]

    chart.bars[0].fillColor = colors.HexColor(
        "#374151"
    )

    chart.bars[1].fillColor = colors.HexColor(
        "#60a5fa"
    )

    chart.valueAxis.labels.fontName = "Helvetica"
    chart.valueAxis.labels.fontSize = 7

    drawing.add(chart)

    return drawing


# =========================================================
# Main PDF Generator
# =========================================================

def generate_pdf_report(report_data):

    buffer = BytesIO()

    document = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=18 * mm,
        leftMargin=18 * mm,
        topMargin=22 * mm,
        bottomMargin=20 * mm,
        title="BTIP Financial & Turnaround Analysis Report",
        author="BTIP",
    )

    styles = create_styles()

    story = []

    company_id = report_data.get("company_id")
    analysis_id = report_data.get("analysis_id")

    financial = report_data.get(
        "financial",
        {}
    )

    crisis = report_data.get(
        "crisis",
        {}
    )

    forecast = report_data.get(
        "forecast",
        {}
    )

    simulation = report_data.get(
        "simulation",
        {}
    )

    recommendations = report_data.get(
        "recommendations",
        []
    )

    # =====================================================
    # Cover
    # =====================================================

    story.append(Spacer(1, 35 * mm))

    story.append(
        Paragraph(
            "BTIP",
            styles["BTIPTitle"],
        )
    )

    story.append(
        Paragraph(
            "BUSINESS TURNAROUND INTELLIGENCE PLATFORM",
            styles["BTIPSubtitle"],
        )
    )

    story.append(Spacer(1, 12 * mm))

    story.append(
        Paragraph(
            "FINANCIAL & TURNAROUND",
            styles["BTIPTitle"],
        )
    )

    story.append(
        Paragraph(
            "ANALYSIS REPORT",
            styles["BTIPTitle"],
        )
    )

    story.append(Spacer(1, 12 * mm))

    cover_data = [
        [
            Paragraph(
                "<b>Company ID</b>",
                styles["Body"],
            ),
            Paragraph(
                safe_text(company_id),
                styles["Body"],
            ),
        ],
        [
            Paragraph(
                "<b>Analysis ID</b>",
                styles["Body"],
            ),
            Paragraph(
                safe_text(analysis_id),
                styles["Body"],
            ),
        ],
        [
            Paragraph(
                "<b>Report Date</b>",
                styles["Body"],
            ),
            Paragraph(
                datetime.now().strftime(
                    "%d %B %Y"
                ),
                styles["Body"],
            ),
        ],
        [
            Paragraph(
                "<b>Report Status</b>",
                styles["Body"],
            ),
            Paragraph(
                "Generated",
                styles["Positive"],
            ),
        ],
    ]

    cover_table = Table(
        cover_data,
        colWidths=[55 * mm, 80 * mm],
    )

    cover_table.setStyle(
        TableStyle(
            [
                (
                    "BOX",
                    (0, 0),
                    (-1, -1),
                    0.7,
                    colors.HexColor("#d1d5db"),
                ),
                (
                    "INNERGRID",
                    (0, 0),
                    (-1, -1),
                    0.5,
                    colors.HexColor("#e5e7eb"),
                ),
                (
                    "BACKGROUND",
                    (0, 0),
                    (0, -1),
                    colors.HexColor("#f3f4f6"),
                ),
                (
                    "VALIGN",
                    (0, 0),
                    (-1, -1),
                    "MIDDLE",
                ),
                (
                    "LEFTPADDING",
                    (0, 0),
                    (-1, -1),
                    10,
                ),
                (
                    "TOPPADDING",
                    (0, 0),
                    (-1, -1),
                    8,
                ),
                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, -1),
                    8,
                ),
            ]
        )
    )

    story.append(cover_table)

    story.append(Spacer(1, 15 * mm))

    story.append(
        Paragraph(
            "Confidential Business Analysis",
            styles["Small"],
        )
    )

    story.append(PageBreak())

    # =====================================================
    # Executive Summary
    # =====================================================

    story.append(
        Paragraph(
            "1. Executive Summary",
            styles["SectionHeading"],
        )
    )

    risk_level = crisis.get(
        "risk_level",
        "N/A"
    )

    crisis_detected = crisis.get(
        "crisis_detected",
        False
    )

    risk_score = crisis.get(
        "risk_score",
        0
    )

    if crisis_detected:
        assessment = (
            "The analysis indicates potential financial "
            "distress. Management attention is recommended "
            "for the identified risk areas."
        )
    else:
        assessment = (
            "The company is currently not showing "
            "critical financial distress according to "
            "the available indicators."
        )

    story.append(
        Paragraph(
            assessment,
            styles["Body"],
        )
    )

    story.append(Spacer(1, 5))

    story.append(
        create_kpi_table(
            [
                (
                    "Risk Score",
                    safe_text(risk_score),
                ),
                (
                    "Risk Level",
                    safe_text(
                        str(risk_level).upper()
                    ),
                ),
                (
                    "Crisis Status",
                    (
                        "Detected"
                        if crisis_detected
                        else "No Crisis"
                    ),
                ),
            ],
            styles,
        )
    )

    story.append(Spacer(1, 8 * mm))

    # =====================================================
    # Financial Overview
    # =====================================================

    story.append(
        Paragraph(
            "2. Financial Overview",
            styles["SectionHeading"],
        )
    )

    story.append(
        create_kpi_table(
            [
                (
                    "Revenue",
                    currency(
                        financial.get("revenue")
                    ),
                ),
                (
                    "Expenses",
                    currency(
                        financial.get("expenses")
                    ),
                ),
                (
                    "Profit",
                    currency(
                        financial.get("profit")
                    ),
                ),
                (
                    "Profit Margin",
                    percentage(
                        financial.get(
                            "profit_margin"
                        )
                    ),
                ),
            ],
            styles,
        )
    )

    story.append(Spacer(1, 5 * mm))

    story.append(
        create_kpi_table(
            [
                (
                    "Cash",
                    currency(
                        financial.get("cash")
                    ),
                ),
                (
                    "Debt",
                    currency(
                        financial.get("debt")
                    ),
                ),
                (
                    "Debt-to-Equity",
                    number(
                        financial.get(
                            "debt_to_equity"
                        )
                    ),
                ),
                (
                    "Net Cash Flow",
                    currency(
                        financial.get(
                            "net_cash_flow"
                        )
                    ),
                ),
            ],
            styles,
        )
    )

    # =====================================================
    # Profitability
    # =====================================================

    story.append(
        Paragraph(
            "3. Profitability Analysis",
            styles["SectionHeading"],
        )
    )

    story.append(
        create_metric_table(
            [
                (
                    "Revenue",
                    currency(
                        financial.get("revenue")
                    ),
                ),
                (
                    "Expenses",
                    currency(
                        financial.get("expenses")
                    ),
                ),
                (
                    "Profit",
                    currency(
                        financial.get("profit")
                    ),
                ),
                (
                    "Profit Margin",
                    percentage(
                        financial.get(
                            "profit_margin"
                        )
                    ),
                ),
            ],
            styles,
        )
    )

    # =====================================================
    # Liquidity
    # =====================================================

    story.append(
        Paragraph(
            "4. Liquidity Analysis",
            styles["SectionHeading"],
        )
    )

    story.append(
        create_metric_table(
            [
                (
                    "Current Assets",
                    currency(
                        financial.get(
                            "current_assets"
                        )
                    ),
                ),
                (
                    "Current Liabilities",
                    currency(
                        financial.get(
                            "current_liabilities"
                        )
                    ),
                ),
                (
                    "Cash",
                    currency(
                        financial.get("cash")
                    ),
                ),
                (
                    "Current Ratio",
                    number(
                        financial.get(
                            "current_ratio"
                        )
                    ),
                ),
            ],
            styles,
        )
    )

    # =====================================================
    # Leverage
    # =====================================================

    story.append(
        Paragraph(
            "5. Leverage Analysis",
            styles["SectionHeading"],
        )
    )

    story.append(
        create_metric_table(
            [
                (
                    "Debt",
                    currency(
                        financial.get("debt")
                    ),
                ),
                (
                    "Equity",
                    currency(
                        financial.get("equity")
                    ),
                ),
                (
                    "Assets",
                    currency(
                        financial.get("assets")
                    ),
                ),
                (
                    "Debt-to-Equity",
                    number(
                        financial.get(
                            "debt_to_equity"
                        )
                    ),
                ),
                (
                    "Debt Ratio",
                    number(
                        financial.get(
                            "debt_ratio"
                        )
                    ),
                ),
            ],
            styles,
        )
    )

    # =====================================================
    # Cash Flow
    # =====================================================

    story.append(
        Paragraph(
            "6. Cash Flow Analysis",
            styles["SectionHeading"],
        )
    )

    story.append(
        create_metric_table(
            [
                (
                    "Operating Cash Flow",
                    currency(
                        financial.get(
                            "operating_cash_flow"
                        )
                    ),
                ),
                (
                    "Investing Cash Flow",
                    currency(
                        financial.get(
                            "investing_cash_flow"
                        )
                    ),
                ),
                (
                    "Financing Cash Flow",
                    currency(
                        financial.get(
                            "financing_cash_flow"
                        )
                    ),
                ),
                (
                    "Net Cash Flow",
                    currency(
                        financial.get(
                            "net_cash_flow"
                        )
                    ),
                ),
            ],
            styles,
        )
    )

    # =====================================================
    # Crisis Detection
    # =====================================================

    story.append(
        Paragraph(
            "7. Crisis & Financial Distress Analysis",
            styles["SectionHeading"],
        )
    )

    story.append(
        create_metric_table(
            [
                (
                    "Risk Score",
                    safe_text(
                        crisis.get(
                            "risk_score"
                        )
                    ),
                ),
                (
                    "Risk Level",
                    safe_text(
                        str(
                            crisis.get(
                                "risk_level"
                            )
                        ).upper()
                    ),
                ),
                (
                    "Crisis Detected",
                    (
                        "YES"
                        if crisis_detected
                        else "NO"
                    ),
                ),
            ],
            styles,
        )
    )

    warnings = crisis.get(
        "warnings",
        []
    )

    story.append(
        Paragraph(
            "Warnings",
            styles["SubHeading"],
        )
    )

    if warnings:
        for warning in warnings:
            story.append(
                Paragraph(
                    f"• {safe_text(warning)}",
                    styles["Warning"],
                )
            )
    else:
        story.append(
            Paragraph(
                "No financial distress warnings were identified.",
                styles["Positive"],
            )
        )

    # =====================================================
    # Forecast
    # =====================================================

    historical = forecast.get(
        "historical_values",
        []
    )

    predictions = forecast.get(
        "predictions",
        []
    )

    if historical or predictions:

        story.append(PageBreak())

        story.append(
            Paragraph(
                "8. Revenue Forecast",
                styles["SectionHeading"],
            )
        )

        if historical:

            story.append(
                Paragraph(
                    "Historical Revenue",
                    styles["SubHeading"],
                )
            )

            historical_rows = []

            for index, value in enumerate(
                historical
            ):
                historical_rows.append(
                    [
                        f"Period {index + 1}",
                        currency(value),
                    ]
                )

            story.append(
                create_metric_table(
                    historical_rows,
                    styles,
                )
            )

        if predictions:

            story.append(
                Paragraph(
                    "Forecasted Revenue",
                    styles["SubHeading"],
                )
            )

            forecast_rows = []

            for index, value in enumerate(
                predictions
            ):
                forecast_rows.append(
                    [
                        f"Forecast Period {index + 1}",
                        currency(value),
                    ]
                )

            story.append(
                create_metric_table(
                    forecast_rows,
                    styles,
                )
            )

            story.append(
                Paragraph(
                    "Historical vs Forecasted Revenue",
                    styles["SubHeading"],
                )
            )

            story.append(
                create_revenue_chart(
                    historical,
                    predictions,
                )
            )

    # =====================================================
    # Recovery Simulation
    # =====================================================

    if simulation:

        story.append(
            Paragraph(
                "9. Recovery Simulation",
                styles["SectionHeading"],
            )
        )

        baseline = simulation.get(
            "baseline",
            {}
        )

        scenario = simulation.get(
            "scenario",
            {}
        )

        projection = simulation.get(
            "projection",
            {}
        )

        comparison = simulation.get(
            "comparison",
            {}
        )

        story.append(
            Paragraph(
                "Current Financial Baseline",
                styles["SubHeading"],
            )
        )

        story.append(
            create_metric_table(
                [
                    (
                        "Revenue",
                        currency(
                            baseline.get(
                                "revenue"
                            )
                        ),
                    ),
                    (
                        "Expenses",
                        currency(
                            baseline.get(
                                "expenses"
                            )
                        ),
                    ),
                    (
                        "Profit",
                        currency(
                            baseline.get(
                                "profit"
                            )
                        ),
                    ),
                    (
                        "Cash",
                        currency(
                            baseline.get(
                                "cash"
                            )
                        ),
                    ),
                    (
                        "Debt",
                        currency(
                            baseline.get(
                                "debt"
                            )
                        ),
                    ),
                ],
                styles,
            )
        )

        story.append(
            Paragraph(
                "Recovery Scenario",
                styles["SubHeading"],
            )
        )

        story.append(
            create_metric_table(
                [
                    (
                        "Revenue Growth",
                        percentage(
                            float(
                                scenario.get(
                                    "revenue_growth",
                                    0
                                )
                            ) * 100
                        ),
                    ),
                    (
                        "Expense Reduction",
                        percentage(
                            float(
                                scenario.get(
                                    "expense_reduction",
                                    0
                                )
                            ) * 100
                        ),
                    ),
                    (
                        "Debt Reduction",
                        percentage(
                            float(
                                scenario.get(
                                    "debt_reduction",
                                    0
                                )
                            ) * 100
                        ),
                    ),
                ],
                styles,
            )
        )

        story.append(
            Paragraph(
                "Projected Recovery",
                styles["SubHeading"],
            )
        )

        story.append(
            create_metric_table(
                [
                    (
                        "Projected Revenue",
                        currency(
                            projection.get(
                                "revenue"
                            )
                        ),
                    ),
                    (
                        "Projected Expenses",
                        currency(
                            projection.get(
                                "expenses"
                            )
                        ),
                    ),
                    (
                        "Projected Profit",
                        currency(
                            projection.get(
                                "profit"
                            )
                        ),
                    ),
                    (
                        "Projected Cash",
                        currency(
                            projection.get(
                                "cash"
                            )
                        ),
                    ),
                    (
                        "Projected Debt",
                        currency(
                            projection.get(
                                "debt"
                            )
                        ),
                    ),
                ],
                styles,
            )
        )

        story.append(
            Paragraph(
                "Baseline vs Recovery",
                styles["SubHeading"],
            )
        )

        story.append(
            create_metric_table(
                [
                    (
                        "Revenue Change",
                        currency(
                            comparison.get(
                                "revenue_change"
                            )
                        ),
                    ),
                    (
                        "Profit Change",
                        currency(
                            comparison.get(
                                "profit_change"
                            )
                        ),
                    ),
                    (
                        "Debt Change",
                        currency(
                            comparison.get(
                                "debt_change"
                            )
                        ),
                    ),
                ],
                styles,
            )
        )

    # =====================================================
    # Recommendations
    # =====================================================

    story.append(
        Paragraph(
            "10. Business Recovery Recommendations",
            styles["SectionHeading"],
        )
    )

    if recommendations:

        recommendation_rows = [
            [
                Paragraph(
                    "<b>Priority</b>",
                    styles["Body"],
                ),
                Paragraph(
                    "<b>Category</b>",
                    styles["Body"],
                ),
                Paragraph(
                    "<b>Recommended Action</b>",
                    styles["Body"],
                ),
            ]
        ]

        for recommendation in recommendations:

            priority = str(
                recommendation.get(
                    "priority",
                    "medium"
                )
            ).upper()

            category = recommendation.get(
                "category",
                "General"
            )

            action = recommendation.get(
                "recommendation",
                ""
            )

            recommendation_rows.append(
                [
                    Paragraph(
                        priority,
                        styles["Body"],
                    ),
                    Paragraph(
                        safe_text(category),
                        styles["Body"],
                    ),
                    Paragraph(
                        safe_text(action),
                        styles["Body"],
                    ),
                ]
            )

        recommendation_table = Table(
            recommendation_rows,
            colWidths=[
                28 * mm,
                35 * mm,
                107 * mm,
            ],
            repeatRows=1,
        )

        recommendation_table.setStyle(
            TableStyle(
                [
                    (
                        "BACKGROUND",
                        (0, 0),
                        (-1, 0),
                        colors.HexColor(
                            "#f3f4f6"
                        ),
                    ),
                    (
                        "GRID",
                        (0, 0),
                        (-1, -1),
                        0.5,
                        colors.HexColor(
                            "#d1d5db"
                        ),
                    ),
                    (
                        "VALIGN",
                        (0, 0),
                        (-1, -1),
                        "TOP",
                    ),
                    (
                        "LEFTPADDING",
                        (0, 0),
                        (-1, -1),
                        7,
                    ),
                    (
                        "RIGHTPADDING",
                        (0, 0),
                        (-1, -1),
                        7,
                    ),
                    (
                        "TOPPADDING",
                        (0, 0),
                        (-1, -1),
                        7,
                    ),
                    (
                        "BOTTOMPADDING",
                        (0, 0),
                        (-1, -1),
                        7,
                    ),
                ]
            )
        )

        story.append(
            recommendation_table
        )

    else:

        story.append(
            Paragraph(
                "No recommendations were generated.",
                styles["Body"],
            )
        )

    # =====================================================
    # Conclusion
    # =====================================================

    story.append(
        Paragraph(
            "11. Turnaround Assessment & Conclusion",
            styles["SectionHeading"],
        )
    )

    if crisis_detected:

        conclusion = (
            "The financial assessment indicates areas that "
            "require management attention. The company should "
            "prioritize liquidity improvement, cash generation, "
            "debt management and the specific recovery actions "
            "identified in this report."
        )

    else:

        conclusion = (
            "The available financial indicators do not "
            "currently indicate critical financial distress. "
            "The company should continue monitoring profitability, "
            "liquidity, leverage, cash flow and forecast trends "
            "to maintain financial stability."
        )

    story.append(
        Paragraph(
            conclusion,
            styles["Body"],
        )
    )

    story.append(Spacer(1, 8 * mm))

    story.append(
        Paragraph(
            "This report was generated automatically by the "
            "Business Turnaround Intelligence Platform (BTIP). "
            "The results are based on the financial data and "
            "analytical models available within the platform.",
            styles["Small"],
        )
    )

    # =====================================================
    # Build
    # =====================================================

    document.build(
        story,
        onFirstPage=draw_header_footer,
        onLaterPages=draw_header_footer,
    )

    buffer.seek(0)

    return buffer